version: '3'

services:
  web:
    build:
      dockerfile: dev.dockerfile
    container_name: web
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - '27017:27017'
    restart: unless-stopped
    command: --config /etc/mongod.conf
    logging:
      driver: none